i2np.bandwidth.inboundBurstKBytes: 22520
i2np.bandwidth.inboundBurstKBytesPerSecond: 128
i2np.bandwidth.inboundKBytesPerSecond: 128
i2np.bandwidth.outboundBurstKBytes: 22520
i2np.bandwidth.outboundBurstKBytesPerSecond: 128
i2np.bandwidth.outboundKBytesPerSecond: 128
i2np.laptopMode: false
i2np.ntcp.autoip: true
i2np.ntcp.enable: true
i2np.udp.addressSources: local,upnp,ssu
i2np.upnp.enable: true
i2p.dir.config: .
prng.buffers: 16
router.dynamicKeys: false
router.maxParticipatingTunnels: 150
router.newsRefreshFrequency: 86400000
router.sharePercentage: 80
router.updatePolicy: notify
router.updateProxyHost: 127.0.0.1
router.updateProxyPort: 4444
router.updateThroughProxy: true
router.updateURL: http://echelon.i2p/i2p/i2pupdate.sud,http://stats.i2p/i2p/i2pupdate.sud,http://www.i2p2.i2p/_static/i2pupdate.sud,http://update.postman.i2p/i2pupdate.sud
router.updateUnsigned: false
routerconsole.lang: en
routerconsole.summaryRefresh: 30
time.disabled: false